### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#1]
As a **User** I can **sign up** so that **I can create a profile**

**Acceptance Criteria:**
- The option should appear on the navigation bar in order to be visible and easily accessible.
- Clicking the sign-up button should direct the user to the sign-up form page.
- The user should be able to register by filling in a name, password, and confirm password fields.
- When a user fills out the registration form incorrectly, feedback should be provided.
- Once the user enters valid user information, the user should be redirected to the sign-in page.

**Tasks:**
- [x] Add a sign-up link to the navbar.
- [x] Connect project to API.
- [x] Create a Sign-Up form.
- [x] Add CSS.
- [x] Add validation to the form fields.
- [x] Provide feedback for the users. 
- [x] Add route for sign-up form to App.js
- [x] Test completed functionality.
