### ISSUE TITLE
USER STORY: Posts page infinite scroll

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#10]
As a **User** I can **scroll endlessly through the posts list** so that **I don't have to click 'next' to view more**

**Acceptance Criteria:**
- The list should be loaded in groups of ten.
- When a user scrolls down near the bottom of the list, the next section of posts should be loaded automatically.
- A loading spinner should be displayed while the next post section is loading.

**Tasks:**
- [x] Add react-infinite-scroll-component library.
- [x] Create FetchMoreData async function.
- [x] Create API requests.
- [x] Add more than 10 posts to test the functionality.
