### ISSUE TITLE
USER STORY: Search for posts

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#11]
As a **User** I can **search for posts with keywords** so that **I can find the posts and explorers I am curious about at the moment**

**Acceptance Criteria:**
- The search bar should be placed at the top.
- The search bar should be displayed on different pages, adapting according to the context.

**Tasks:**
- [x] Add a search bar with a query method to a PostsPage.
- [x] Create API request.
- [x] Add interval timer to the query method.
- [x] Test completed functionality
