### ISSUE TITLE
USER STORY: View posts of followed explorers

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#12]
As a **logged-in user** I can **view content filtered by explorers I follow** so that **I can stay up to date with their posts**

**Acceptance Criteria:**
- Choose explorers to follow.
- Filter posts by followed explorers.
- Display the results in the "Feed".

**Tasks:**
- [x] Make it possible to follow other explorers ( #18 )
- [x] Add an icon for "Following" to the navigation bar.
- [x] Create a Route.
- [x] Add a message if there are no posts to show.
