### ISSUE TITLE
USER STORY: View posts of explorers in the favorite list 

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#13]
As a **logged-in user** I can **view content filtered by explorers I have in my favorite list** so that **I can stay up-to-date with their posts**

**Acceptance Criteria:**
- Add explorers to the list of favorites.
- Filter posts by explorers on that list.
- Display the results in the "Favorites".

**Tasks:**
- [x] Make it possible to add other explorers to the favorite list ( #20  )
- [x] Add an icon for "Favorites" to the navigation bar.
- [x] Create a Route.
- [x] Add a message if there are no posts to show.
