### ISSUE TITLE
USER STORY: View an explorer profile

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#14]
As a **User** I can **view other explorers' profiles** so that **I can see their posts and learn more about them**

**Acceptance Criteria:**
- All the users, regardless of login status, should be able to view others' profiles.
- Each explorer profile should display the number of posts, actual posts, number of followers and favorites, and number of users the explorer is following and has on the favorite list.
- Bio | dream destination | Region the explorer wants to explore | are optional fields.

**Tasks:**
- [x] Create an ExplorerPage component.
- [x] Create API requests.
- [x] Add a Route for the ExplorerPage component to the App.js.
- [x] Display the number of posts, number of followers and favorites, and number of users the explorer is following and has on the favorite list.
- [x] For logged-in users:
   - [x] Display the "follow" button if the user is not following another explorer.
   - [x]  Display the "unfollow" button if the user is already following another explorer.
   - [x]  Display the "fan" button if the user has not added another explorer to their favorite list.
   - [x]  Display the "unfan" button if the user already added another explorer to their favorite list.
- [x] Test completed functionality.
