### ISSUE TITLE
USER STORY: View most popular explorer profiles

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#15]
As a **User** I can **easily view the most followed explorers** so that **know which popular profiles to check out**

**Acceptance Criteria:**
-  All the users should be able to have access to information about the most popular explorers.
- Each explorer profile in the list should feature a link to the profile, username, and image.
- Each explorer profile should include buttons to follow/unfollow and add/remove to favorites if the user is logged in.

**Tasks:**
- [x] Create popular explorers rofiles component.
- [x] Create an Explorer component to display users' avatars and link to their pages.
- [x] Make API request (get explorers ordered by followers_count in descending order)
- [x] Display loading spinner to the user while loading.
- [x] For logged-in users:
  - [x] Display the "follow" button if the user is not following another explorer.
  - [x] Display the "unfollow" button if the user is already following another explorer.
  - [x] Display the "fan" button if the user has not added another explorer to their favorite list.
  - [x] Display the "unfan" button if the user already added another explorer to their favorite list.
