### ISSUE TITLE
USER STORY: Edit explorer profile

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#16]
As a **logged-in User** I can **edit my explorer profile** so that **I can update my page with my latest details**

**Acceptance Criteria:**
- An "edit" profile button link should be visible to logged-in users on their profile.
- Clicking the "edit" profile button should direct the user to the edit profile form page.
- The form fields in the edit profile form should be pre-populated with the latest data.
- Upon successful submission, the user should be redirected back to their profile.

**Tasks:**
- [x] Create a dropdown for the explorer page. 
- [x] Add the "Edit Explorer profile" button to the Explorer page dropdown.
- [x] Add EditExplorerForm component.
- [x] Create a Route for Edit Explorer form to App.js
- [x] Make API request  (get - to catch the existing data, put - to update)
- [x] Add alert messages to let the user know if something went wrong.
- [x] Redirect user back to their profile on successful form submission.
- [x] Test completed functionality.
