### ISSUE TITLE
USER STORY: Upload default profile image

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#17]
As a **User** I can **use a default profile image** so that **I don’t have to upload my own**

**Acceptance Criteria:**
- When a user first signs up, a new profile should be automatically created for them.
- The user's new profile should contain a default profile image.
- The user should be able to upload their own image later on.

**Tasks:**
- [x] Upload default profile image to Cloudinary.
- [x] Add a path to the image in the models.
- [x] Create an Avatar component.
- [x] Test functionality.
