### ISSUE TITLE
USER STORY: Follow explorers

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#18]
As a **logged-in User** I can **follow another user** so that **I easily can stay updated with any new posts that they create**

**Acceptance Criteria:**
- Once logged in, the user should be able to see a "follow" button next to each explorer (if they have not been followed earlier).
- The button should not be displayed next to the user's own profile.
- After the button is clicked:
   - The user's following count should be increased by 1.
   - The followed explorer's followed count should be increased by 1.
   - The "Unfollow" button should be displayed.
   - The followed explorer's posts should be visible on the "Feed" page.

**Tasks:**
- [x] Add a "follow" button to the Explorer page and popular Explorers components.
- [x] Add a follow method.
- [x] Make a request.
- [x] Add ternary to display the button only to logged-in users who are not following another user.
- [x] Add ternary to check so the users can not follow themselves.
- [x] When the button is clicked:
  - [x] Add functionality to display the "unfollow" button when the "follow" button is clicked.
  - [x] Increase another user's followed count by one.
  - [x] Increase the following_count for the user that is clicking the "follow" button. 
- [x] Test completed functionality.
