### ISSUE TITLE
USER STORY: Unfollow explorers

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#19]
As a **logged-in User** I can **unfollow other explorers** so that **I can remove updates of that user from my feed**

**Acceptance Criteria:**
- Once logged in, the user should be able to see an "unfollow" button next to each followed explorer.
- The button should not be displayed next to the user's own profile.
- After the button is clicked:
   - The user's following count should be decreased by 1.
   - The followed explorer's followers_count should be decreased by 1.
   - The "Follow" button should be displayed.
   - The newly unfollowed explorer's post should not be visible on the "Following" page.

**Tasks:**
- [x] Add an "unfollow" button to the Explorer page and popular Explorers components.
- [x] Add ternary to display the button only to logged-in users who are already following another user.
- [x] Make a "delete" request.
  -  When the button is clicked:
  - [x] Add functionality to display the "follow" button when the "unfollow" button is clicked.
  - [x] Decrease another user's followers_count by one.
  - [x] Decrease the following_count for the user that is clicking the "unfollow" button by one.
