### ISSUE TITLE
USER STORY: Sign into account

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#2]
As a **User** I can **sign into my account** so that **I can access all the site's features**

**Acceptance Criteria:**
- The option should appear on the navigation bar in order to be visible and easily accessible.
- The login feature enables users to access their accounts and utilize all functions available on the site.
- Filling in the form correctly should direct the user to the homepage.
- Upon successful login, the user's profile link and other pages restricted to logged-in users should be displayed in the navbar.

**Tasks:**
- [x]  Add a sign-in link to the navbar.
- [x]  Create a Sign-In form.
- [x]  Add onChange and onSubmit methods.
- [x]  Add route for sign-in component to App.js
- [x]  Add validation to the form fields.
- [x]  Provide feedback for the users.
- [x] Add conditional rendering to display correct icons upon successful login.  ( #36 )
- [x] Test completed functionality.
