### ISSUE TITLE
USER STORY: Add explorers to favorite list

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#20]
As a **logged-in User** I can **add other users to my favorite list** so that **I easily see the latest from accounts I like the most**

**Acceptance Criteria:**
- Once logged in, the user should be able to see an "Add to :star: " button next to each explorer.
- The button should not be displayed next to the user's own profile.
- After the button is clicked:
   - The user's favoriting count should be increased by 1.
   - The favorited explorer's favorited count should be increased by 1.
   - The "Remove from :star:" button should be displayed.
   - The newly favorited explorer's posts should be visible on the ":star:" page.

**Tasks:**
- [x]  Add a "fan" button to the Explorer page and popular Explorers components.
- [x] Add a fan method.
- [x] Make a request.
- [x] Add ternary to display the button only to logged-in users who do not have another user on their favorite list.
- [x] Add ternary to check so the users can not fan themselves.
- [x]  When the button is clicked:
   - [x] Add functionality to display the "unfan" button when the "fan" button is clicked.
   - [x] Increase another user's favorited_count by one.
   - [x] Increase the favoriting_count for the user that is clicking the "fan" button.
- [x] Test completed functionality.
