### ISSUE TITLE
USER STORY: Remove explorers from favorite list

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#21]
As a **logged-in User** I can **remove other users from my favorite list** so that **I can remove updates of that user from my "Favorites" page**

**Acceptance Criteria:**
- Once logged in, the user should be able to see a "Fan" button next to the explorers who earlier were added to the favorite list.
- The button should not be displayed next to the user's own profile.
- After the button is clicked:
   - The user's favoriting count should be decreased by 1.
   - The favorited explorer's favourites_count should be decreased by 1.
   - The "Fan" button should be displayed.
   - The selected explorer's posts should be visible on the "Favorites" page.

**Tasks:**
- [x] Add an "unfan" button to the Explorer page and popular Explorers components.
- [x] Add ternary to display the button only to logged-in users who have already added another user to their favorite list.
- [x] Make a "delete" request.
  - When the button is clicked:
  - [x] Add functionality to display the "fan" button.
  - [x] Decrease another user's favourites_count by one.
  - [x] Decrease the favoriting_count for the user that is clicking by one.
