### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#22]
As a **User** I can **view comments on posts** so that **can read what other users think about the posts**

**Acceptance Criteria:**
- When the user clicks on a post, they should be directed to a page where they can see all the comments left on that post.
- Comments should include the username, profile image, comment text, and information about how long ago the comment was posted.
- If there are no comments left yet, the user should receive the information about that.
- Only logged-in users can leave comments (#23)

**Tasks:**
- [x] Make it possible for logged-in users to leave comments ( #23 ).
- [x] Create a Comment component to display the comments on the post detailed page.
- [x] Make a request to API to fetch the comments.
- [x] Add a message to the user if there are no comments yet.
- [x] Test completed functionality.
