### ISSUE TITLE
USER STORY: Create a comment

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#23]
As a **logged-in User** I can **comment on posts** so that **I can engage with the community and the author**

**Acceptance Criteria:**
- Once logged in, create comment form should be visible under the post details on the post detail page.
- Clicking the comment form submit button should add the comment at the top of the post page comment list.
- Information displayed: 
  - Username;
  - Profile image/default image;
  - The comment text;
  - Information about how long ago a comment was posted.
- The number of comments should be increased by 1.

**Tasks:**
- [x] Create CommentCreateForm.
- [x] Add CommentCreateForm to the post detailed view.
- [x] Add the logic to display comments to the user.
- [x] Increase the comments_count by 1.
- [x] Test completed functionality.
