### ISSUE TITLE
USER STORY: Edit a comment

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#24]
As a **logged-in User** I can **edit my comment** so that **I can correct mistakes**

**Acceptance Criteria:**
- An "edit" button icon should be visible on any comments made by a user
- When the "edit" button is clicked, it should open the edit comment form component. 
- The form fields should be automatically filled with the content of the comment that was posted.
- If a user edits and then clicks the "save" button, the edited content should be displayed.
- If a user clicks the cancel button, the form should be closed, with the original comment remaining visible.

**Tasks:**
- [x]  Add React-Bootstrap custom dropdown menu.
- [x] Create a CommentEditPage.
- [x] Make API requests.
- [x] Make sure that the field is pre-populated.
- [x] Test completed functionality.
