### ISSUE TITLE
USER STORY: Delete a comment

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#25]
As a **logged-in User** I can **delete a comment posted by me** so that **I can remove the ones I don't want to be posted**

**Acceptance Criteria:**
- After logging in, users should be able to view a "delete" button next to all of their comments.
- When the "delete" button is clicked, the comment should be removed from the list.
- The comment list should be updated to display a new list without the deleted comment.
- The number of comments should be decreased by one.

**Tasks:**
- [x]  Add React-Bootstrap custom dropdown menu.
- [x]  Add a confirmation message to check whether the user is sure about deleting.
- [x]  Decrement Post's comments_count by 1.
- [x] Test completed functionality.
