### ISSUE TITLE
USER STORY: Like a post

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#26]
As a **logged-in User** I can **like other users' posts** so that **I can show my appreciation to the author**

**Acceptance Criteria:**
- The option (icon) should appear both on the posts page and in the detailed post view.
- The option should be accessible only to logged-in users.
- User should not be able to like their own posts.
- Clicking the "like" icon should add one like to the post like count.

**Tasks:**
- [x] Add a Like icon to the detailed post page.
- [x] Use the ternary operator to check the user's current status and whether the user is the owner of the post.
- [x] If the user is not logged in: display a message saying that they need to log in to like the post.
- [x] If the user owns the post: display a message saying they can't like their own post.
- [x] Add handleLike function;
- [x] Add one like to the like_count when the user clicks the like icon.
- [x] Test completed functionality.
