### ISSUE TITLE
USER STORY: Unlike a post

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#27]
As a **logged-in User** I can **unlike a post** so that **I can remove a like if I don't want to like the post anymore**

**Acceptance Criteria:**
- The option (icon) should appear both on the posts page and in the detailed post view.
- The option should be accessible only to logged-in users.
- Users should be able to unlike the posts they earlier liked.
- Clicking the "unlike" icon should remove one like from the post like count.

**Tasks:**
- [x] Add a Like icon.
- [x] User ternary operator to check if the user already liked a post.
- [x] Add handleUnlike function:
- [x] Decrease the like_count by 1 when the user clicks to unlike.
- [x] Test completed functionality.
