### ISSUE TITLE
USER STORY: View all posts by a specific explorer

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#28]
As a **User** I can **view all the posts by a specific explorer** so that **I can catch up on their latest posts**

**Acceptance Criteria:**
- The option should be accessible when visiting explorers' profiles.
- It should be possible to view the posts by using the search field and the username of the explorer as a keyword.

**Tasks:**
- [x] Three first tasks in  #14 need to be completed.
- [x] Make a second API request to fetch the explorerPosts.
- [x] If the array is not empty, add an InfiniteScroll component.
- [x] If the array is empty, display a message to the user saying that the selected explorer hasn't posted anything yet..
