### ISSUE TITLE
USER STORY: Change account username

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#29]
As a **logged-in User** I can **change my username** so that **other users will see my updated username on my profile**

**Acceptance Criteria:**
- An "edit" username icon should appear on a user profile.
- Clicking the button should direct the user to the change username form page.
- The form field should be pre-populated with the user's current username.
- Changing the field and submitting the form should redirect the user back to their profile.
- The new username should be displayed.

**Tasks:**
- [x] Add the "change username" button to the Explorer dropdown menu.
- [x] Add edit username form component with on-change and on-submit methods.
- [x] Make API requests.
- [x] Create a Route for Edit username form to App.js
- [x] Redirect user back to their profile on successful form submission.
- [x] Test completed functionality.
