### ISSUE TITLE
USER STORY: Sign out of account

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#3]
As a **User** I can **sign out of my account** so that **I can close the application and navigate away from the page**

**Acceptance Criteria:**
- The option should appear on the navigation bar to be visible and easily accessible.
- Clicking the sign-out button should sign out the user and redirect them to the homepage of the site.
- The navigation bar component should re-render the icons for logged-out users to prevent them from accessing restricted content.

**Tasks:**
- [x] Add logout functionality.
- [x] Add conditional rendering to display correct icons upon successful sign-out. (#36)
- [x] Test completed functionality.
