### ISSUE TITLE
USER STORY: Change account password

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#30]
As a **logged-in User** I can **update my password** so that **I can keep my profile secure**

**Acceptance Criteria:**
- An "edit" password icon should appear on a user profile.
- Clicking the button should direct the user to the change password form page.
- Changing the field and submitting the form should redirect the user back to their profile.
- The user should be able to log in with the newly updated password next time.

**Tasks:**
- [x] Add the "change password" button to the Explorer dropdown menu.
- [x] Add edit password form component with on-change and on-submit methods.
- [x] Create a Route for Edit password form to App.js
- [x] Make a post request.
- [x] Add alert messages to let the user know if something went wrong.
- [x] Redirect user back to their profile on successful form submission.
- [x] Test completed functionality.
