### ISSUE TITLE
USER STORY: Bookmark posts

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#31]
As a **logged-in User** I can **bookmark different posts** so that **I can save and revisit them later**

**Acceptance Criteria:**
- The option should be accessible under all the posts published by other explorers. 
- Only logged-in users should be able to bookmark posts.
-  When the "bookmark" icon is clicked:
   - The post should be added to the bookmarks page of the site.
   - The amount of "bookmarks" under the post should be increased by 1.

**Tasks:**
- [x]  Add a Bookmark icon to the posts pages.
- [x] Use the ternary operator to check the user's current status.
- [x]  If the user is not logged in: display a message saying that they need to log in to bookmark the post.
- [x]  Add handleBookmark function;
- [x] Increase bookmark_count by 1 when the user clicks the bookmark icon.
- [x] Test completed functionality.
