### ISSUE TITLE
USER STORY: Remove bookmark label

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#32]
As a **logged-in User** I can **remove bookmark labels from posts** so that **they are no longer displayed on the bookmarks page**

**Acceptance Criteria:**
- The option should be accessible for logged-in users under all their earlier bookmarked posts.
- When the icon is clicked:
   - The post should be removed from the bookmarks page of the site.
   - The amount of "bookmarks" under the post should be decreased by 1.

**Tasks:**
- [x]  Add a Bookmark icon.
- [x] User ternary operator to check if the user already bookmarked a post.
- [x] Add handleUnbookmark function:
- [x] Decrease the bookmark_count by 1.
- [x] Test completed functionality.
