### ISSUE TITLE
USER STORY: View most popular posts

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#33]
As a **User** I can **see the top 10 posts** so that **I can see what posts are the most popular**

**Acceptance Criteria:**
- A list of the most popular posts should be visible on the home page.
- The popular list should be limited to 10.
- The posts should be sorted by most liked in descending order.

**Tasks:**
- [x] Create a popular posts component.
- [x] Create a MostLikedPost component to display posts' images and titles.
- [x] Make API request (get posts ordered by likes_count in descending order)
- [x] Display loading spinner to the user while loading.
- [x] Test completed functionality.
