### ISSUE TITLE
USER STORY: Get feedback

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#34]
As a **User** I can **get corresponding feedback after taking an action** so that **I know whether my actions were successfully run or not**

**Acceptance Criteria:**
- Information about whether the user's actions were successful or not should be displayed.
- Alert message should automatically disappear after 3 seconds.

**Tasks:**
- [x] Install SweetAlerts for React (_npm install sweetalert2_)
- [x] Import Swal in all the files alerts will be used (_import Swal from 'sweetalert2'_).
- Add Alert messages to: 
  - [x] Post (create, update, delete).
  - [x] Comments (create, update, delete).
  - [x] Explorer profile (create, update, delete).
