### ISSUE TITLE
USER STORY: Navigate seamlessly

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#35]
As a **User** I can **navigate through pages quickly** so that **I can view content seamlessly without page refresh**

**Acceptance Criteria:**
- Routes should be set up on all navbar links.

**Tasks:**
- [x] Create Routes for each navbar link.
- [x] Add icons to be displayed in the navbar.
- [x] Create components.
- [x] Test completed functionality.
