### ISSUE TITLE
USER STORY: Navigation Bar - Conditional rendering

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#36]
As a **User** I can **see the appropriate site access options** so that **I can easily access links to change my login status**

**Acceptance Criteria:**
- If the user is logged out, the navigation bar should display links for sign-up and sign-in.
- If the user is logged in, a sign-out link should be visible in the navigation bar.
- As soon as the user's login status changes, the links in the navigation bar should be updated automatically to reflect the change.

**Tasks:**
- [x] Add conditional rendering logic to the navbar component.
- [x] Add context logic to be able to check the current user state.
- [x] Create a function to update the current user state upon successful login.
- [x] Add logout functionality.
- [x] Test completed functionality.
