### ISSUE TITLE
USER STORY: Comments infinite scroll

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#37]
As a **User** I can **scroll endlessly through the comments list** so that **I don't have to click 'next' to view more comments**

**Acceptance Criteria:**
- The list should be loaded in groups of ten.
- When a user scrolls down near the bottom of the list, the next section of comments should be loaded automatically.
- A loading spinner should be displayed while the next comment section is loading.

**Tasks:**
- [x] Add react-infinite-scroll-component library.
- [x] Create FetchMoreData async function.
- [x] Create API requests.
- [x] Add more than 10 comments to test the functionality.
