### ISSUE TITLE
USER STORY: Filter posts by category

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#38]
As a **User** I can **filter the posts list by category** so that **I can easily see all posts relating to one particular category**

**Acceptance Criteria:**
- All the explorers should select a category when publishing a post.
- Categories should be displayed on the site in the form of a dropdown menu.
- Once a category is selected, the posts list is filtered to only show events within that category.
- If there are no posts in the selected category, the user should get the information about that.

**Tasks:**
- [x] Add "region" (category in this project) to filteset_fileds on the backend.
- [x] Make API request.
- [x] Display filter possibility on the PostsPage.
- [x] Test completed functionality.
