### ISSUE TITLE
USER STORY: Like a comment

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#39]
As a **logged-in User** I can **like other users' comments** so that **I can show my appreciation to their opinion**

**Acceptance Criteria:**
- The option (icon) should appear on the detailed post view.
- The option should be accessible only to logged-in users.
- User should not be able to like their own comments.
- Clicking the "like" icon should add one like to the comment like count.

**Tasks:**
- [x] Add a Like icon to the comment section.
- [x] Use the ternary operator to check the user's current status and whether the user is the owner of the comment.
- [x] If the user is not logged in: display a message saying that they need to log in to like the comment.
- [x] If the user owns the comment: display a message saying they can't like their own comment.
- [x] Add handleLikeComment function;
- [x] Increase comment like_count by 1.
- [x] Test completed functionality.
