### ISSUE TITLE
USER STORY: View Navigation Bar

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#4]
As a **User** I can **view a navbar from every page** so that **I can easily navigate between pages**

**Acceptance Criteria:**
- The navigation bar should be visible to the user from all pages of the site.
- It should be responsive on different devices.
- Links should have easily understandable names.
- By clicking on the title/logo the user should be redirected to the home page every time.
- Some pages should be hidden based on whether the user is logged in or not.

**Tasks:**
- [x] Create a Navbar component.
- [x] Style the Navbar, and make it responsive.
- [x] Create Routes.
- [x] Wire up the links.
- [x] Test completed functionality.
