### ISSUE TITLE
USER STORY: Create/publish a post

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#5]
As a **logged-in User** I can **post an image** so that **I can share my travel experience with others**

**Acceptance Criteria:**
- The "Add a post" link should be placed in the navigation bar to be visible and easily accessible.
- It should be displayed only for logged-in users.
- The user should be directed to the post form component when clicking the link.
- Once the form is submitted, the user should be redirected to the post page showing all details of the newly created post.

**Tasks:**
- [x] Add an "Add Post" icon.
- [x] Create a PostCreateForm component.
- [x] Add a Route for the component into App.js
- [x] Add error handling and validation.
- [x] Send Post data to the API.
- [x] Test completed functionality.
