### ISSUE TITLE
USER STORY: Edit a post

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#6]
As a **logged-in User** I can **update my own posts** so that **correct errors or add new information**

**Acceptance Criteria:**
- An "edit" button should be visible on all post pages for posts owned by the user.
- The user should be directed to a page containing a form with pre-populated fields.
- Upon successful submission, the user should be redirected back to the updated post page.

**Tasks:**
- [x] Add React-Bootstrap custom dropdown menu.
- [x] Create an EditPage.
- [x] Add a Route for PostEditForm component into App.js
- [x] Make sure that the fields are pre-populated with the correct post id.
- [x] Make API requests.
- [x] Test completed functionality.
