### ISSUE TITLE
USER STORY: Delete a post

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#7]
As a **logged-in User** I can **delete my own posts** so that **I can remove the ones I don’t want to share anymore**

**Acceptance Criteria:**
- An "delete" button should be visible on all post pages for posts owned by the user.
- The user should be prompted with a confirmation question before the deletion process.
- Clicking the delete button should delete the post and redirect the user back to the home page.

**Tasks:**
- [x]  Add React-Bootstrap custom dropdown menu.
- [x] Make API requests.
- [x] Add a confirmation message to check whether the user is sure about deleting.
- [x] Test completed functionality.
