### ISSUE TITLE
USER STORY: View list of all posts

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#8]
As a **User** I can **see a list of all posts** so that **I can browse through them and find inspiration**

**Acceptance Criteria:**
- All the users should be able to see all the posts on the home page of the site.
- The user should be able to view detailed post information by clicking on each post.
- Most recent posts should be displayed first.

**Tasks:**
- [x] Create PostsPage component.
- [x] Create API requests.
- [x] Add a loading spinner.
- [x] Add a ternary operator to check if the data is loaded.
- [x] Add a ternary operator to check if there are some results to display.
- [x] Display a message and an image if there are no results to show.
- [x] Test completed functionality.
