### ISSUE TITLE
USER STORY: View details of a post

### ISSUE THREAD

**Issue by Kattis91** [Kattis91/with-travel-in-mind#9]
As a **User** I can **click on a post to view the full post details** so that **I can find out more information about the post**

**Acceptance Criteria:**
- All the users, regardless of login status, should be able to view details.
- Clicking on an individual post, the user should be redirected to the post's full detail page.

**Tasks:**
- [x] Create a Post page.
- [x] Add Route for the page into App.js
- [x] Create API request for a post ID.
- [x] Create a Post component.
- [x] Test completed functionality.
